services:
  msinventory:
    build: .
    container_name: msinventory
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true